### ISSUE TITLE
new jetstream client; Graceful shutdown (similar to old interface Drain method

### ISSUE THREAD

**Issue by tpihl** [nats-io/nats.go#1328] opened 2023-06-21 08:41 UTC
It is very unclear how to make a graceful shutdown (regardless of type of consumer).

Will ConsumeContext.Stop prevent the next call to msghandler or continue to call it until all "in-flight" (MaxAckPending) is processed? And how do I know when that is complete. Or did the Stop() leave them hanging to timeout before they re-transmit? Or where they NAKed by the new client?

Same question with the iterator, what happens with msg queued in the client when it.Stop() is called, and is there a graceful shutdown available.

The usecase is ofc that an undefined number (up to MaxAckPending msgs will be unavailable until they timeout even though they could have been processed during shutdown after a DisInterest() call to stop adding more unprocessed msgs.

What are the developers suggestion to support graceful shutdown of msg-by-msg processing from a consumer?

**Comment by piotrpio** [comment] 2023-07-20 10:22
Hey @tpihl, sorry for the late response. Thanks for reporting the issue, we will be working on resolving this problem one way or another. The problem is, while for push consumers `Drain()` has little "lag", because client simply informs the server that it no longer wants to receive messages, for pull consumers we will have to wait until all pull requests are fully processed before we complete draining (this may take up to `PullExpiry`, by default 30s). But as I said, we will be working on adding this feature soon.

**Comment by derekcollison** [comment] 2023-07-20 17:24
Hey @piotrpio let's discuss, I think there is a way where you do not have to wait.

**Comment by AndrewDK** [comment] 2023-10-23 17:37
Any update?

**Comment by ragnaros2046** [comment] 2024-01-08 23:35
Any update?

**Comment by piotrpio** [comment] 2024-01-13 11:37
Hey folks, sorry it took so long. With the now release [nats.go@v1.32.0](https://github.com/nats-io/nats.go/releases/tag/v1.32.0) we've added a `Drain()` method working with both `ConsumeContext` and `MessagesContext`. Unlike stop, it not only cancels the active pull requests but also waits until all messages in the client buffer are processed.

**Closed by piotrpio** 2024-01-13 11:37 UTC
Labels: feature

**Comment by thomas-maurice** [comment] 2024-07-14 17:56
@piotrpio I have noticed a strange behaviour with `Drain`, it does not seem to wait for the in flight messages to be processed. I am observing a behaviour where if I call `Drain` on a consumer that has an artificially long processing time (by adding a sleep in it) then my program exits before the processing is done, `Drain` appears to not be blocking. Is it a bug or am I doing something wrong ?

**Comment by francescov1** [comment] 2025-02-03 20:51
@thomas-maurice Im finding the same, have you found a solution?

**Comment by piotrpio** [comment] 2025-02-03 21:22
@francescov1 there were follow-up issues to this one: #1673 and #1672. In short, `Drain()` being non-blocking is intentional since it can potentially take a very long time. However, we added a `ConsumeContext.Closed()` which waits on a channel until `Consume` finishes processing messages - which used together with `Drain()` should give you the behavior you want: https://pkg.go.dev/github.com/nats-io/nats.go/jetstream#ConsumeContext
