### ISSUE TITLE
PullSubscribe does not support reconnection

### ISSUE THREAD

**Issue by oliverpool** [nats-io/nats.go#890] opened 2022-01-26 16:31 UTC
## Defect

I created a `PullSubscribe` on Jetstream. Everything is fine (and messages can be `Fetch`ed) as long as the server does not restart.

When I restart the server, every call to `Fetch` fails with a `timeout`.

#### Versions of `nats.go` and the `nats-server` if one was involved:

`nats.go v1.13.0`
`nats-server v2.7.1` (docker, latest image)

#### OS/Container environment:

Arch Linux

#### Steps or code to reproduce the issue:

Run a nats server and the following code.
When it reads `restart NATS NOW`, please stop and restart nats.

```go
package main

import (
	"fmt"
	"time"

	"github.com/nats-io/nats.go"
)

func main() {
	fmt.Println(run())
}
func run() error {
	nc, err := nats.Connect("localhost:4222",
		nats.DisconnectErrHandler(func(nc *nats.Conn, err error) {
			fmt.Println("nats", "disconnected", "reason", err)
		}),
		nats.ReconnectHandler(func(nc *nats.Conn) {
			fmt.Println("nats", "reconnected")
		}))
	if err != nil {
		return err
	}

	// Create JetStream Context
	js, err := nc.JetStream()
	if err != nil {
		return err
	}

	// Create a Stream
	_, err = js.AddStream(&nats.StreamConfig{
		Name:     "ORDERS",
		Subjects: []string{"ORDERS.*"},
		MaxMsgs:  100,
	})
	if err != nil {
		return err
	}
	// Publish 50 messages
	for i := 0; i < 50; i++ {
		_, err = js.PublishAsync("ORDERS.scratch", []byte(fmt.Sprintf("message-%d", i)))
		if err != nil {
			return err
		}
	}
	select {
	case <-js.PublishAsyncComplete():
		fmt.Println("All published.")
	case <-time.After(5 * time.Second):
		fmt.Println("Did not resolve in time")
	}

	// Durable Pull Consumer
	pullsub, err := js.PullSubscribe("ORDERS.*", "MONITOR")
	if err != nil {
		return err
	}
	msgs, err := pullsub.Fetch(10)
	if err != nil {
		return err
	}
	for _, m := range msgs {
		fmt.Printf("Received a JetStream message: %s\n", string(m.Data))
	}
	go func() {
		time.Sleep(5 * time.Second)
		fmt.Println("consuming again")
		for {
			msgs, err := pullsub.Fetch(10)
			if err != nil {
				fmt.Printf("could not fetch: %v\n", err)
				continue
			}
			for _, m := range msgs {
				fmt.Printf("Received a JetStream message: %s\n", string(m.Data))
			}
		}
	}()
	fmt.Println("restart NATS NOW")
	time.Sleep(30 * time.Second)
	return nil
}
```

#### Expected result:

I would expect the 2nd `Fetch` to succeed.

#### Actual result:

The 2nd `Fetch` fails continuously with a `timeout`:
```
All published.
Received a JetStream message: message-0
Received a JetStream message: message-1
Received a JetStream message: message-2
Received a JetStream message: message-3
Received a JetStream message: message-4
Received a JetStream message: message-5
Received a JetStream message: message-6
Received a JetStream message: message-7
Received a JetStream message: message-8
Received a JetStream message: message-9
restart NATS NOW
nats disconnected reason EOF
consuming again
nats reconnected
could not fetch: nats: timeout
could not fetch: nats: timeout
could not fetch: nats: timeout
could not fetch: nats: timeout
```

**Comment by wallyqs** [comment] 2022-02-23 15:06
Taking a look now.

**Comment by wallyqs** [comment] 2022-02-28 14:57
With the script above I haven't been able to reproduce, I get for example:

```
2022/02/28 06:52:55 All published.
2022/02/28 06:52:55 Received a JetStream message: message-0
2022/02/28 06:52:55 Received a JetStream message: message-1
2022/02/28 06:52:55 Received a JetStream message: message-2
2022/02/28 06:52:55 Received a JetStream message: message-3
2022/02/28 06:52:55 Received a JetStream message: message-4
2022/02/28 06:52:55 Received a JetStream message: message-5
2022/02/28 06:52:55 Received a JetStream message: message-6
2022/02/28 06:52:55 Received a JetStream message: message-7
2022/02/28 06:52:55 Received a JetStream message: message-8
2022/02/28 06:52:55 Received a JetStream message: message-9
2022/02/28 06:52:55 restart NATS NOW
2022/02/28 06:52:59 nats disconnected reason EOF
2022/02/28 06:53:00 consuming again
2022/02/28 06:53:03 nats reconnected
2022/02/28 06:53:03 Received a JetStream message: message-10
2022/02/28 06:53:03 Received a JetStream message: message-11
2022/02/28 06:53:03 Received a JetStream message: message-12
2022/02/28 06:53:03 Received a JetStream message: message-13
2022/02/28 06:53:03 Received a JetStream message: message-14
2022/02/28 06:53:03 Received a JetStream message: message-15
2022/02/28 06:53:03 Received a JetStream message: message-16
```

@cstaud @staust is the stream where you run into this with a similar setup as in the original program?

```go
	_, err = js.AddStream(&nats.StreamConfig{
		Name:     "ORDERS",
		Subjects: []string{"ORDERS.*"},
		MaxMsgs:  100,
	})
```

**Comment by cstaud** [comment] 2022-02-28 15:12
Hi, we did it like so:
```golang
func setupStream(subjects []string, jetStream natsClient.JetStreamContext) error {
	streamConfig := &natsClient.StreamConfig{
		Name:        streamName,
		Description: "Stream for queueing build and publish tasks",
		Subjects:    subjects,
		Retention:   natsClient.WorkQueuePolicy,
		MaxAge:      24 * time.Hour,
		Storage:     natsClient.FileStorage,
		Replicas:    1,
	}
	_, errUpdateStream := jetStream.UpdateStream(streamConfig)
	if errUpdateStream != nil {
		if errUpdateStream.Error() == "stream not found" {
			_, errAddStream := jetStream.AddStream(streamConfig)
			if errAddStream != nil {
				log.WithError(errAddStream).WithField("streamConfig", streamConfig).Error("could not add stream")
				return errAddStream
			}
			return nil
		}
		log.WithField("streamConfig", streamConfig).WithError(errUpdateStream).Error("could not update stream")
		return errUpdateStream
	}
	return nil
}
```

**Comment by oliverpool** [comment] 2022-02-28 16:16
> could it be that you simply not have the state persisted, so on restart there is no such stream and pull would timeout?

Yes, I was running from docker, but I can't remember if I had mounted the persistent volume or not...

My [actual problem](https://github.com/nats-io/nats.go/discussions/888) using a `ChanQueueSubscribe`, so I don't really care about this issue anymore (i.e. from my side, you can close the issue)

**Comment by wallyqs** [comment] 2022-02-28 16:40
I used both `main` from server/client and `nats.go v1.13.0` / `nats-server v2.7.1` and could not reproduce.

**Comment by wallyqs** [comment] 2022-02-28 17:06
Does not seem to reproduce with latest so closing for now then, likely the issue was missing volume from docker, that makes sense.

**Closed by wallyqs** 2022-02-28 17:06 UTC
Labels: bug
