### ISSUE TITLE
Problems with load balancing in a queue group

### ISSUE THREAD

**Issue by jonasmatthias** [nats-io/nats.go#610] opened 2020-11-27 12:29 UTC
I try to figure out an issue with load balancing between subscribers in a queue group. My take from the documentation is, that the load should be randomly distributed between the queue subscribers. The service has 15 pods subscribed to the same subject in a  queue group and most of them receive messages at a rate of 200 Hz, one subscriber is at 800 Hz and some are in between. 

We use a cluster with 3 NATS.IO servers ([similar to this statefulset](https://gist.github.com/wallyqs/c566c856b7119645fd7e11056374c584)). The queue subscribers are distributed 6-5-4 over the servers. Most subscribers receive NATS messages at a rate of 200 Hz, whereas one subscriber gets 800 Hz and is overloaded. This leads to a backlog of pending messages and as a result messages are dropped by the [go library](https://godoc.org/github.com/nats-io/nats.go).

What confuses me, is that this imbalance is constant over time until the autoscaler add or removes a pod. After scaling, the load is distributed differently, but still not even with some subscribers at 200 Hz and other at 600 Hz.

The following table of the metrics in the subscriber pods is sorted by the NATS server address:
![image](https://user-images.githubusercontent.com/53558955/100448859-42078380-30b3-11eb-8c44-22d07bcbf00c.png)

**Comment by ripienaar** [comment] 2020-11-27 12:31
Do you also have a metric for how long the pod spends processing a message? It could be that this pod is taking longer to process messages and so lags?

Distribution is generally random yes, you'd see some variance but given a big enuogh subset of data distribution is mosly equal.

**Comment by jonasmatthias** [comment] 2020-11-27 15:22
Yes, the processing duration is typically below 1 ms. However, for the overloaded instance is is longer. But why would it receive a higher message rate than the other instances?

<img width="659" alt="image" src="https://user-images.githubusercontent.com/53558955/100452149-dc1dfa80-30b8-11eb-85fc-b57c911f780d.png">

I added the message handling duration to the table:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/53558955/100463515-3ffdee80-30cc-11eb-9713-f712219f9f8f.png">

**Comment by jonasmatthias** [comment] 2020-11-27 15:39
But the message rates are unevenly distributed even when the load is lower. In this screenshot for a period of more than one hour with handling durations well below 200 µs.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/53558955/100464883-abe15680-30ce-11eb-814d-e923b282a7b9.png">

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/53558955/100465009-da5f3180-30ce-11eb-87d7-decc5e76352d.png">

**Comment by derekcollison** [comment] 2020-11-27 15:48
What version of the server and what is the server config setup?

**Comment by jonasmatthias** [comment] 2020-11-27 15:52
Docker image `nats:2.1.0`

You can see the server config in this [nats-statefulset.yaml](https://gist.github.com/wallyqs/c566c856b7119645fd7e11056374c584#file-nats-statefulset-yaml-L29-L44).

**Comment by jonasmatthias** [comment] 2020-11-27 16:08
Here is our ConfigMap in Kubernetes:
```
pid_file: "/var/run/nats/nats.pid"
http: 8222
cluster {
  port: 6222
  routes [
    nats://nats-0.nats:6222
    nats://nats-1.nats:6222
    nats://nats-2.nats:6222
  ]
  cluster_advertise: $CLUSTER_ADVERTISE
  connect_retries: 30
}
```

The `$CLUSTER_ADVERTISE` seems wrong...

**Comment by derekcollison** [comment] 2020-11-27 16:42
Same behavior with nats:2.1.9?

Will loop in @wallyqs on the k8s stuff.

**Comment by kozlovic** [comment] 2020-11-27 19:04
Check the release notes: the release 2.1.4 states:
```
Messages to queue subscriptions are not distributed evenly. Thanks to @harrisa1 for the report (#1215)
```
PR: https://github.com/nats-io/nats-server/pull/1215.

I am going to close this assuming that this has been fixed. You should use the latest v2.1.9. Should the problem remain, we will re-open this issue. Thanks!

**Closed by kozlovic** 2020-11-27 19:04 UTC

**Comment by jonasmatthias** [comment] 2020-11-30 09:54
Yes, my problem sound exactly like https://github.com/nats-io/nats-server/issues/1144 and updating to 2.1.9 solved it. Now the message rate is evenly distributed between the subscribers.

Thanks for your help and sorry for not checking the nats-server release notes more carefully.

**Comment by kozlovic** [comment] 2020-11-30 16:00
@jonasmatthias No worries and glad the issue is resolved!
