### ISSUE TITLE
There is some probleam in createNewRequestAndSend nats.go:2708

### ISSUE THREAD

**Issue by hubinix** [nats-io/nats.go#537] opened 2020-01-03 06:12 UTC
this code block wrtoe like this:
	if createSub {
		// Make sure scoped subscription is setup only once.
		var err error
		nc.respSetup.Do(func() { err = nc.createRespMux(ginbox) })
		if err != nil {
			return nil, token, err
		}
	}
if   err = nc.createRespMux(ginbox)  is failed by broken network or other problem.
err is not nil
the code is return and request is failed.

BUT the  nc.Subscribe(respSub, nc.respHandler)  can not run again,
 because of the nc.respSetup.Do.
The server can not recover automaticly. All request always return error.

func (nc *Conn) Request(subj string, data []byte, timeout time.Duration) (*Msg, error) {
	if nc == nil {
		return nil, ErrInvalidConnection
	}

	nc.mu.Lock()
	// If user wants the old style.
	if nc.Opts.UseOldRequestStyle {
		nc.mu.Unlock()
		return nc.oldRequest(subj, data, timeout)
	}

	mch, token, err := nc.createNewRequestAndSend(subj, data)
	if err != nil {
		return nil, err
	}

**Comment by hubinix** [comment] 2020-01-03 06:18
i think the use of sync.Once is not correct.

**Comment by kozlovic** [comment] 2020-01-06 16:29
@derekcollison I wonder if we should not have a create sub version that does not get the lock so that we could create the sub for the wildcard sub within the conn lock in createNewRequestAndSend(). It is true that the use of sync.Once does not work should createRespMux() return an error. (that is, all subsequent requests for this connection will always timeout).

**Comment by derekcollison** [comment] 2020-01-06 21:51
I think that sounds like a good idea. Thanks @hubinix for the report!

**Comment by kozlovic** [comment] 2020-01-06 22:18
Was working on that, but trying to write a test and realize that createRespMux() is unlikely to fail: the call there nc.Subscribe() cannot fail simply because there is a network issue. The only reason it could fail is if it is called with invalid params (which won't be the case) or if connection was closing, which then the issue is moot since user cannot call Request() anymore.
I can still make the code changes, but not sure how to test this.

**Comment by derekcollison** [comment] 2020-01-06 22:19
I think we would need a test to make the changes.

**Comment by kozlovic** [comment] 2020-01-06 22:20
So would need advice on what test will show the issue with current code so that we verify the change works..

**Comment by derekcollison** [comment] 2020-01-06 22:40
@hubinix have you seen an issue with this in practice? Is it reproducible?

**Comment by kozlovic** [comment] 2020-01-06 22:44
I can write a fake test that artificially set the connection's status to CLOSED to make the createRespMux() call fail on first request, and after putting back I see that the following request does timeout (as expected with the Once.Do() call), but this is really artificial.. with that said, with the code change the second Request() would then succeed.

**Comment by derekcollison** [comment] 2020-01-06 22:58
Let's see what @hubinix reports back first.

**Comment by hubinix** [comment] 2020-01-07 04:25
@derekcollison  
we use nats.go for a SLG game。when our game server start ，the game autorun a heart beat to broadcast something to other servers or players immediately。but by mistake ，one of our company‘s programer don't check  the connectivity of the nats. that is,we try send a rpc message  to other servers,but the nats has not been connected.
so we fix our code,and try to report this problem to you.
because this problem puzzled us for months.

**Comment by hubinix** [comment] 2020-01-07 04:33
@derekcollison 
it is not stable reproducible,but happend everyday.
because our game is  in the developing,we restart our server  very frequently。

**Comment by derekcollison** [comment] 2020-01-07 12:55
ok thanks for that feedback. @kozlovic let's proceed with a fix when we can.

**Comment by kozlovic** [comment] 2020-01-07 15:53
@hubinix But if the NATS connection is not created, then it would be nil, and Request() should exit right away. So again, not sure how this can happen. I will still proceed with a fix, but then not sure this is capturing the issue that you have experienced.

**Comment by kozlovic** [comment] 2020-01-07 21:55
@hubinix Would love if you could provide some pseudo-code that shows your sequence of initializing the NATS connection and the first request. Like I said, I fail to understand how the steps you described would lead to the Once.Do() issue you have reported.
I am still publishing a PR related to that, but as I explained, I had to come up with a completely artificial test to simulate the issue, which is not ideal.

**Closed** 2020-01-15 16:15 UTC
