### ISSUE TITLE
Go Mod Revision Error (unknown revision 9f4d16f)

### ISSUE THREAD

**Issue by FarhanSajid1** [nats-io/nats.go#493] opened 2019-07-12 19:59 UTC
I am getting a revision error through go mod, and was wondering if you could guide me into the right direction. When running go mod for my project, even though nats is not a direct depedency, I receive this error through go mod. 

github.com/nats-io/nats.go@v1.8.2-0.20190607221125-9f4d16fe7c2d: unknown revision 9f4d16fe7c2d

**Comment by wallyqs** [comment] 2019-07-12 20:18
Go modules is silently bumping to 1.8.2 pseudo version (does not exists) to a merge commit that somehow went lost in master. According to Go modules maintainers you can potentially workaround this issue by doing the following:

```
replace github.com/nats-io/nats.go v1.8.2-0.20190607221125-9f4d16fe7c2d => github.com/nats-io/nats.go v1.8.1
```

To avoid that you need to figure out which dependency is causing this and make it use a explicit tag version, not a pseudo-version.

**Comment by wallyqs** [comment] 2019-07-12 20:20
More info about this issue could be found here: https://github.com/golang/go/issues/33076

**Comment by ayzu** [comment] 2019-07-12 20:33
@wallyqs

As far as I understand, the problem steams from the fact that this commit 9f4d16fe7c2d existed in the past. And some other projects such as micro/go-plugins mentioned it as a dependency.

Then this commit was removed from the history via force push. Is that the case?

**Comment by wallyqs** [comment] 2019-07-12 20:40
Don't know the exact reason why the commit got lost to be honest, it looks like it is a merge commit from a PR though the commits themselves from that branch got merged.

**Comment by bcmills** [comment] 2019-07-12 21:21
Aha! That commit is indeed from a PR, and was merged as `3d6c21bef4f7fe0ad308983c0769c2caa3a2ba15` (presumably due to some sort of rebasing?).

golang/go#31191 explicitly filters out commits of that sort, although I'm not actually sure whether that fix made it into `go1.12.7`.

**Comment by bcmills** [comment] 2019-07-12 21:23
Since that commit was never intended to be accessible in the first place, this is arguably a defect in micro/go-plugins rather than nats-io/nats.go.

**Comment by wallyqs** [comment] 2019-07-12 21:39
thanks @bcmills for the help handling this issue. Also as you mention it seems that GOPROXY could help in this case:

```
docker run -it golang
GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/micro/go-plugins
```

seems to work ok as well.

**Comment by wallyqs** [comment] 2019-07-14 21:08
Still not sure how this happened but closing since dependency with the issue is fixed https://github.com/micro/go-plugins/pull/375 If this was caused due to https://github.com/golang/go/issues/31191 then looks this is prevented in Go 1.13.

**Closed by wallyqs** 2019-07-14 21:08 UTC

**Comment by samzhao1985** [comment] 2019-07-23 08:00
This worked for me! Thanks for sharing!

go mod edit -replace=github.com/nats-io/nats.go@v1.8.2-0.20190607221125-9f4d16fe7c2d=github.com/nats-io/nats.go@v1.8.1
